services:
  postgres-dev:
    image: postgres:15-alpine
    env_file:
      - ./db.env
    restart: always
    ports:
      - 5432:5432
    networks:
      - api
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
      - ./db-backup/:/db-backup/

  mariadb-dev:
    image: mariadb:11.1
    env_file:
      - ./db.env
    restart: always
    ports:
      - 3306:3306
    networks:
      - api
    volumes:
      - mariadb-data-dev:/var/lib/mariadb/data
      - ./db-backup/:/db-backup/

  mongodb-dev:
    image: mongo:5.0.12
    restart: always
    env_file:
      - ./db.env
    volumes:
      - mongo-data-dev:/data/db
      - ./db-backup/:/db-backup/
    ports:
      - 27017:27017
    networks:
      - api

  # web client for postgres & mariadb
  adminer:
    image: adminer:4.8.1
    restart: always
    ports:
      - 18890:8080
    networks:
      - api

  # web client for mongo
  # sample connection string: mongodb://user:password@mongodb-dev:27017/fiber-starter?authSource=admin&sslmode=disable
  nosqlclient:
    image: mongoclient/mongoclient
    ports:
      - 3100:3000
    networks:
      - api

  # this section is not related to db, but just put the redis & rabbitmq etc. here
  rabbitmq-dev:
    image: rabbitmq:3-management-alpine
    restart: always
    env_file:
      - ./db.env
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data-dev:/var/lib/rabbitmq/
    networks:
      - api

  # for caching
  redis-dev:
    image: redis:7-alpine
    restart: always
    ports:
      - 6379:6379
    networks:
      - api
    # command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    # volumes:
    #   - cache:/data

  # for caching
  memcached-dev:
    image: memcached:alpine
    restart: always
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    ports:
      - 11211:11211
    networks:
      - api

volumes:
  pg-data-dev:
  mariadb-data-dev:
  mongo-data-dev:
  rabbitmq-data-dev:

networks:
  api:
    external: true
