#!/usr/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

go_test(){
if ! go test -count=1 -race ./...; then
  echo "Tests failed. Fix errors and try committing again."
  exit 1
fi
}

go_fmt(){
  for file in $(git diff --cached --name-only --diff-filter=ACM | grep ".go$"); do
    if ! go fmt "$file"; then
      echo "go fmt failed on staged file '$file'. Please fix the errors and try again."
      exit 1
    fi
    git add "$file"
  done
}

# format go files
go_fmt

# Running go tests
go_test
